platform :ios, '9.0'
use_frameworks!

target 'DexonWalletSDK_Example' do
  pod 'DexonWalletSDK', :path => '../'
  pod 'DexonWalletSDK/Web3', :path => '../'
  pod 'SnapKit'
  pod 'AloeStackView'
  pod 'CryptoSwift'
  pod 'web3swift.pod'

  target 'DexonWalletSDK_Tests' do
    inherit! :search_paths    
  end
end
